name: ESLint

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - '*.md'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1

      - name: Install dependencies
        run: npm i

      - name: Check ESLint
        run: npm run lint

      - name: Check Format
        run: npm run format
